<?php

namespace Mrapps\OnesignalBundle\Repository;

/**
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserPlayerRepository extends \Doctrine\ORM\EntityRepository
{
    public function unsetUserPlayers(User $user = null) {

        if($user !== null) {

            $em = $this->getEntityManager();

            $players = array();
            $idsPlayers = array();

            //Elimina relazioni
            $ups = $em->getRepository('MrappsOnesignalBundle:UserPlayer')->findBy(array('user' => $user));
            foreach ($ups as $up) {
                $player = $up->getPlayer();
                if($player !== null && !in_array($player->getId(), $idsPlayers)) {
                    $idsPlayers[] = $player->getId();
                    $players[] = $player;
                }

                $em->remove($up);
            }
            $em->flush();

            //Elimina i Player inattivi
            foreach ($players as $p) {
                $this->deleteInactivePlayer($p);
            }

            return true;
        }

        return false;
    }
}
